### ISSUE TITLE
JSFiddle demo has wrong path to the module

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/value-in-legend#3]
New path is https://rawgithub.com/highcharts/value-in-legend/master/value-in-legend.js but the demo (http://jsfiddle.net/highcharts/DVvdZ/?utm_source=website&utm_medium=embed&utm_campaign=DVvdZ) is using the old URL and fails to load the file - old URL: https://rawgithub.com/highslide-software/value-in-legend/master/value-in-legend.js

**Comment by TorsteinHonsi** [comment]
Thanks!
