### ISSUE TITLE
Exception on setting Legend property "enabled : false"

### ISSUE THREAD

**Issue by SudhanshuDabral** [highcharts/value-in-legend#4]
I am using Value in legend plugins.
When i am setting Legend property "enabled : false" it hides the legend box but on mouse over of chart it throws error in highcharts js.

"Unhandled exception at line 27, column 373 in Highchart.js
JavaScript runtime error: Array.prototype.forEach: 'this' is null or undefined"

**Comment by KacperMadej** [comment]
Hi @SudhanshuDabral 

Thank you for reporting about the problem.
Please add a live demo of the problem, so we could debug it, test possible solution and suggest a workaround - a temporary solution, until a proper fix will be provided.

**Comment by SudhanshuDabral** [comment]
Hi @KacperMadej 
     Thanks for reply, you can find a live demo at following url.
https://jsfiddle.net/ashishsim2/gcL70myn/7/

**Comment by SudhanshuDabral** [comment]
![issue](https://user-images.githubusercontent.com/26308409/43127483-6fe0634e-8ee4-11e8-9805-e311d1f4d8a8.png)

**Comment by KacperMadej** [comment]
The plugin is very small, so the fastest way to resolve this problem as a workaround is to use changed code like in this demo: https://jsfiddle.net/BlackLabel/her078k3/1/

Added features:
- checking if legend is disabled
(if there's no items in legend then the `legend.allItems` array is empty, so doesn't causes the error)

**Comment by SudhanshuDabral** [comment]
Thanks @KacperMadej  for your solution.
